# Generated by Django 5.1.6 on 2025-02-20 12:29

import uuid

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("arches_lingo", "0002_load_lingo_lists"),
    ]

    def create_function(apps, schema_editor):
        Node = apps.get_model("models", "Node")
        Function = apps.get_model("models", "Function")
        FunctionXGraph = apps.get_model("models", "FunctionXGraph")
        grouping_node = (
            Node.objects.filter(
                alias="appellative_status",
                graph__slug="scheme",
                graph__source_identifier=None,
            )
            .select_related("nodegroup", "graph")
            .get()
        )
        func = Function.objects.create(
            # Needed until https://github.com/archesproject/arches/issues/10958
            pk=uuid.uuid4(),
            name="Validate Appellative Status",
            functiontype="node",
            description="Prevent multiple preferred labels in any language.",
            defaultconfig={"triggering_nodegroups": [str(grouping_node.pk)]},
            modulename="validate_appellative_status",
            classname="ValidateAppellativeStatus",
            component=None,
        )
        FunctionXGraph.objects.create(
            # Needed until https://github.com/archesproject/arches/issues/10958
            pk=uuid.uuid4(),
            function=func,
            graph=grouping_node.graph,
            config=func.defaultconfig,
        )

    def remove_function(apps, schema_editor):
        Function = apps.get_model("models", "Function")
        Function.objects.get(classname="ValidateAppellativeStatus").delete()

    operations = [migrations.RunPython(create_function, remove_function)]
