# Generated by Django 4.2.8 on 2024-01-05 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arches_rdm', '0001_initial'),
        ('models', '10260_add_iiifmanifest_globalid'),
    ]

    add_migrate_rdm = """
        INSERT INTO etl_modules (
            etlmoduleid,
            name,
            description,
            etl_type,
            component,
            componentname,
            modulename,
            classname,
            config,
            icon,
            slug,
            helpsortorder,
            helptemplate,
            reversible)
        VALUES (
            '11cad3ca-e155-44b1-9910-c50b3def47f6',
            'RDM Migration',
            'Migrate concepts and schemes to the new RDM',
            'import',
            'views/components/etl_modules/migrate-rdm',
            'migrate-rdm',
            'migrate_rdm.py',
            'RDMMigrator',
            '{"bgColor": "#ffa564", "circleColor": "#ffd2b1", "show": true}',
            'fa fa-usb',
            'migrate-rdm',
            6,
            'migrate-rdm-help',
            true);
        """
    remove_migrate_rdm = """
        DELETE FROM load_staging WHERE loadid IN (SELECT loadid FROM load_event WHERE etl_module_id = '11cad3ca-e155-44b1-9910-c50b3def47f6');
        DELETE FROM load_event WHERE etl_module_id = '11cad3ca-e155-44b1-9910-c50b3def47f6';
        DELETE FROM etl_modules WHERE etlmoduleid = '11cad3ca-e155-44b1-9910-c50b3def47f6';
    """

    operations = [
        migrations.RunSQL(
            add_migrate_rdm,
            remove_migrate_rdm,
        ),
    ]
